export const IMAGE_COMPRESSION_CONFIG = Symbol('IMAGE_COMPRESSION_CONFIG');
export const FILE_VALIDATION_CONFIG = Symbol('FILE_VALIDATION_CONFIG');
export const STORAGE_PROVIDER_SERVICE = Symbol('STORAGE_PROVIDER_SERVICE');
