export const STORAGE_CONSTANTS = {
  IMAGE_COMPRESSION_CONFIG: 'IMAGE_COMPRESSION_CONFIG',
  FILE_VALIDATION_CONFIG: 'FILE_VALIDATION_CONFIG',
  STORAGE_PROVIDER_SERVICE: 'STORAGE_PROVIDER_SERVICE',
};
