// Generated by i18n-validator

interface DropdownsErrorsCategorynotfoundParams {
  id: string | number
}

interface DropdownsErrorsCategorynameexistsParams {
  name: string | number
}

interface DropdownsErrorsDropdownnotfoundParams {
  id: string | number
}

interface DropdownsErrorsDropdownnameexistsParams {
  name: string | number
}

interface DropdownsErrorsOptionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnameexistsParams {
  name: string | number
}

interface DropdownsErrorsSelectionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnotindropdownParams {
  optionId: string | number; dropdownId: string | number
}

interface DropdownsErrorsMaxdepthexceededParams {
  maxDepth: string | number
}

interface DropdownsErrorsCategorymismatchParams {
  categoryId: string | number; dropdownCategoryId: string | number
}

interface DropdownsErrorsOptionnotfoundindropdownParams {
  optionId: string | number; dropdownName: string | number
}

interface DropdownsErrorsDropdownnotfoundincategoryParams {
  dropdownName: string | number; categoryName: string | number
}

interface DropdownsErrorsCannotdeleteoptionreferencedParams {
  optionName: string | number
}

interface DropdownsErrorsCannotdeletedropdownreferencedParams {
  dropdownName: string | number
}

interface DropdownsErrorsDuplicateoptionnamesinrequestParams {
  duplicates: string | number
}

interface DropdownsErrorsOptionnamealreadyexistsParams {
  optionName: string | number
}

interface DropdownsErrorsCannotupdateoptionsnotfoundParams {
  missingOptions: string | number
}

interface EmergencyaidrequestErrorsNotfoundParams {
  id: string | number
}

interface EmployeesErrorsNotfoundParams {
  id: string | number
}

interface FamilymembersErrorsNotfoundwithidParams {
  id: string | number
}

interface GuardsErrorsAccessdeniedParams {
  permissions: string | number
}

interface PersonsErrorsNotfoundParams {
  id: string | number
}

interface PersonsErrorsNotfoundbynameParams {
  name: string | number
}

interface PipesValidationIslessthanorequalParams {
  property: string | number; relatedProperty: string | number
}

interface PipesValidationOnlyoneoffieldsParams {
  fields: string | number
}

interface PipesValidationExactlyoneoffieldsParams {
  fields: string | number
}

interface PipesValidationMultiplevalidationerrorsParams {
  errors: string | number
}

interface PipesValidationMaxgreaterthanorequalminParams {
  maxField: string | number; maxValue: string | number; minField: string | number; minValue: string | number
}

interface PipesValidationInvalidsyriaphoneParams {
  property: string | number
}

interface PipesValidationInvalidbooleanvalueParams {
  key: string | number
}

interface PipesValidationMustnotequalParams {
  property: string | number; relatedProperty: string | number
}

interface ReceivedassistanceErrorsNotfoundParams {
  id: string | number
}

interface RolesErrorsPermissionnotfoundParams {
  id: string | number
}

interface RolesErrorsUsernotfoundParams {
  userId: string | number
}

interface RolesErrorsSystemusernotfoundParams {
  systemUserId: string | number
}

interface RolesErrorsPermissionnotassignedParams {
  permissionId: string | number; systemUserId: string | number
}

interface RolesErrorsDuplicatepermissionidsParams {
  duplicateIds: string | number
}

interface RolesErrorsPermissionsnotfoundParams {
  missingIds: string | number
}

interface RolesErrorsRolenotfoundParams {
  id: string | number
}

interface RolesErrorsRolenameexistsParams {
  name: string | number
}

interface RolesErrorsRolenameinuseParams {
  name: string | number
}

interface SupportersErrorsNotfoundParams {
  id: string | number
}

interface SupportersErrorsChildsponsorshipNotfoundParams {
  id: string | number
}

interface SystemusersErrorsNotfoundParams {
  id: string | number
}

interface SystemusersSuccessDeletedParams {
  id: string | number
}

interface TrainingcoursesTrainingcoursesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesTrainingcoursesSuccessDeletedParams {
  name: string | number
}

interface TrainingcoursesCoursebatchesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesCoursebatchesErrorsBatchnumberexistsParams {
  batchNumber: string | number; courseId: string | number
}

interface TrainingcoursesCoursebatchesSuccessDeletedParams {
  batchNumber: string | number; trainingCourseName: string | number
}

interface TrainingcoursesPersoncoursebatchesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesPersoncoursebatchesErrorsAlreadyenrolledParams {
  familyMemberId: string | number; courseBatchId: string | number
}

interface UploadsErrorsNotfoundParams {
  id: string | number
}

const TranslationKeys = {
  'app.hello_world': 'app.hello_world',
  'auth.errors.invalid_credentials': 'auth.errors.invalid_credentials',
  'auth.errors.invalid_or_expired_access_token': 'auth.errors.invalid_or_expired_access_token',
  'dropdowns.errors.cannot_create_subcategory': 'dropdowns.errors.cannot_create_subcategory',
  'dropdowns.errors.cannot_delete_core_category': 'dropdowns.errors.cannot_delete_core_category',
  'dropdowns.errors.cannot_delete_dropdown_referenced': 'dropdowns.errors.cannot_delete_dropdown_referenced',
  'dropdowns.errors.cannot_delete_option_referenced': 'dropdowns.errors.cannot_delete_option_referenced',
  'dropdowns.errors.cannot_update_options_not_found': 'dropdowns.errors.cannot_update_options_not_found',
  'dropdowns.errors.category_has_children': 'dropdowns.errors.category_has_children',
  'dropdowns.errors.category_has_dropdowns': 'dropdowns.errors.category_has_dropdowns',
  'dropdowns.errors.category_mismatch': 'dropdowns.errors.category_mismatch',
  'dropdowns.errors.category_name_exists': 'dropdowns.errors.category_name_exists',
  'dropdowns.errors.category_not_found': 'dropdowns.errors.category_not_found',
  'dropdowns.errors.dropdown_has_options': 'dropdowns.errors.dropdown_has_options',
  'dropdowns.errors.dropdown_name_exists': 'dropdowns.errors.dropdown_name_exists',
  'dropdowns.errors.dropdown_not_found': 'dropdowns.errors.dropdown_not_found',
  'dropdowns.errors.dropdown_not_found_in_category': 'dropdowns.errors.dropdown_not_found_in_category',
  'dropdowns.errors.duplicate_option_names_in_request': 'dropdowns.errors.duplicate_option_names_in_request',
  'dropdowns.errors.duplicate_options_not_allowed': 'dropdowns.errors.duplicate_options_not_allowed',
  'dropdowns.errors.invalid_selection_type': 'dropdowns.errors.invalid_selection_type',
  'dropdowns.errors.max_depth_exceeded': 'dropdowns.errors.max_depth_exceeded',
  'dropdowns.errors.multiple_selection_requires_at_least_one_option': 'dropdowns.errors.multiple_selection_requires_at_least_one_option',
  'dropdowns.errors.option_has_selections': 'dropdowns.errors.option_has_selections',
  'dropdowns.errors.option_name_already_exists': 'dropdowns.errors.option_name_already_exists',
  'dropdowns.errors.option_name_exists': 'dropdowns.errors.option_name_exists',
  'dropdowns.errors.option_not_found': 'dropdowns.errors.option_not_found',
  'dropdowns.errors.option_not_found_in_dropdown': 'dropdowns.errors.option_not_found_in_dropdown',
  'dropdowns.errors.option_not_in_dropdown': 'dropdowns.errors.option_not_in_dropdown',
  'dropdowns.errors.selection_not_found': 'dropdowns.errors.selection_not_found',
  'dropdowns.errors.single_selection_exists': 'dropdowns.errors.single_selection_exists',
  'dropdowns.errors.single_selection_requires_one_option': 'dropdowns.errors.single_selection_requires_one_option',
  'emergency-aid-request.errors.cannot_approve_non_pending': 'emergency-aid-request.errors.cannot_approve_non_pending',
  'emergency-aid-request.errors.cannot_cancel_unmodifiable': 'emergency-aid-request.errors.cannot_cancel_unmodifiable',
  'emergency-aid-request.errors.cannot_disburse_non_approved': 'emergency-aid-request.errors.cannot_disburse_non_approved',
  'emergency-aid-request.errors.cannot_reject_non_pending': 'emergency-aid-request.errors.cannot_reject_non_pending',
  'emergency-aid-request.errors.not_found': 'emergency-aid-request.errors.not_found',
  'employees.errors.already_employee': 'employees.errors.already_employee',
  'employees.errors.cannot_delete_with_system_account': 'employees.errors.cannot_delete_with_system_account',
  'employees.errors.not_found': 'employees.errors.not_found',
  'families.family_book_number_exists': 'families.family_book_number_exists',
  'families.family_book_number_exists_another': 'families.family_book_number_exists_another',
  'families.form_number_exists': 'families.form_number_exists',
  'families.form_number_exists_another': 'families.form_number_exists_another',
  'families.not_found': 'families.not_found',
  'families.request_number_exists': 'families.request_number_exists',
  'families.request_number_exists_another': 'families.request_number_exists_another',
  'family-members.errors.cannot_change_relation_with_sponsorships': 'family-members.errors.cannot_change_relation_with_sponsorships',
  'family-members.errors.family_already_has_father': 'family-members.errors.family_already_has_father',
  'family-members.errors.family_already_has_guardian': 'family-members.errors.family_already_has_guardian',
  'family-members.errors.gender_relation_mismatch': 'family-members.errors.gender_relation_mismatch',
  'family-members.errors.not_found': 'family-members.errors.not_found',
  'family-members.errors.not_found_with_id': 'family-members.errors.not_found_with_id',
  'family-members.errors.only_children_can_be_sponsored': 'family-members.errors.only_children_can_be_sponsored',
  'family-members.errors.person_already_family_member': 'family-members.errors.person_already_family_member',
  'family-needs.errors.not_found': 'family-needs.errors.not_found',
  'guards.errors.access_denied': 'guards.errors.access_denied',
  'guards.errors.access_token_required': 'guards.errors.access_token_required',
  'guards.errors.token_issued_before_login': 'guards.errors.token_issued_before_login',
  'guards.errors.token_issued_before_password_change': 'guards.errors.token_issued_before_password_change',
  'guards.errors.user_not_authenticated': 'guards.errors.user_not_authenticated',
  'interviews.errors.not_found': 'interviews.errors.not_found',
  'persons.errors.email_exists': 'persons.errors.email_exists',
  'persons.errors.father_name_exists': 'persons.errors.father_name_exists',
  'persons.errors.full_name_exists': 'persons.errors.full_name_exists',
  'persons.errors.name_no_parent_exists': 'persons.errors.name_no_parent_exists',
  'persons.errors.national_id_exists': 'persons.errors.national_id_exists',
  'persons.errors.not_found': 'persons.errors.not_found',
  'persons.errors.not_found_by_name': 'persons.errors.not_found_by_name',
  'persons.errors.person_details_exists': 'persons.errors.person_details_exists',
  'pipes.validation.array_required': 'pipes.validation.array_required',
  'pipes.validation.exactly_one_of_fields': 'pipes.validation.exactly_one_of_fields',
  'pipes.validation.id_integer': 'pipes.validation.id_integer',
  'pipes.validation.id_not_empty': 'pipes.validation.id_not_empty',
  'pipes.validation.id_positive': 'pipes.validation.id_positive',
  'pipes.validation.invalid_boolean_value': 'pipes.validation.invalid_boolean_value',
  'pipes.validation.invalid_syria_phone': 'pipes.validation.invalid_syria_phone',
  'pipes.validation.is_less_than_or_equal': 'pipes.validation.is_less_than_or_equal',
  'pipes.validation.max_greater_than_or_equal_min': 'pipes.validation.max_greater_than_or_equal_min',
  'pipes.validation.min_max_validation_failed': 'pipes.validation.min_max_validation_failed',
  'pipes.validation.multiple_validation_errors': 'pipes.validation.multiple_validation_errors',
  'pipes.validation.must_not_equal': 'pipes.validation.must_not_equal',
  'pipes.validation.only_one_of_fields': 'pipes.validation.only_one_of_fields',
  'pipes.validation.positive_integer_required': 'pipes.validation.positive_integer_required',
  'received-assistance.errors.family_member_mismatch': 'received-assistance.errors.family_member_mismatch',
  'received-assistance.errors.not_found': 'received-assistance.errors.not_found',
  'roles.errors.cannot_change_superadmin_permissions': 'roles.errors.cannot_change_superadmin_permissions',
  'roles.errors.cannot_modify_protected_users': 'roles.errors.cannot_modify_protected_users',
  'roles.errors.duplicate_permission_ids': 'roles.errors.duplicate_permission_ids',
  'roles.errors.permission_ids_not_exist': 'roles.errors.permission_ids_not_exist',
  'roles.errors.permission_not_assigned': 'roles.errors.permission_not_assigned',
  'roles.errors.permission_not_found': 'roles.errors.permission_not_found',
  'roles.errors.permissions_not_found': 'roles.errors.permissions_not_found',
  'roles.errors.role_has_users': 'roles.errors.role_has_users',
  'roles.errors.role_name_exists': 'roles.errors.role_name_exists',
  'roles.errors.role_name_in_use': 'roles.errors.role_name_in_use',
  'roles.errors.role_not_found': 'roles.errors.role_not_found',
  'roles.errors.role_protected': 'roles.errors.role_protected',
  'roles.errors.superadmin_role_protected': 'roles.errors.superadmin_role_protected',
  'roles.errors.system_user_not_found': 'roles.errors.system_user_not_found',
  'roles.errors.user_not_found': 'roles.errors.user_not_found',
  'supporters.errors.already_supporter': 'supporters.errors.already_supporter',
  'supporters.errors.child_sponsorship.child_already_has_active_sponsorship': 'supporters.errors.child_sponsorship.child_already_has_active_sponsorship',
  'supporters.errors.child_sponsorship.child_already_sponsored': 'supporters.errors.child_sponsorship.child_already_sponsored',
  'supporters.errors.child_sponsorship.not_found': 'supporters.errors.child_sponsorship.not_found',
  'supporters.errors.child_sponsorship.only_children_can_be_sponsored': 'supporters.errors.child_sponsorship.only_children_can_be_sponsored',
  'supporters.errors.not_found': 'supporters.errors.not_found',
  'system-users.errors.employee_has_system_account': 'system-users.errors.employee_has_system_account',
  'system-users.errors.not_found': 'system-users.errors.not_found',
  'system-users.errors.username_taken': 'system-users.errors.username_taken',
  'system-users.success.deleted': 'system-users.success.deleted',
  'training-courses.course-batches.errors.batch_number_exists': 'training-courses.course-batches.errors.batch_number_exists',
  'training-courses.course-batches.errors.end_date_before_start_date': 'training-courses.course-batches.errors.end_date_before_start_date',
  'training-courses.course-batches.errors.not_found': 'training-courses.course-batches.errors.not_found',
  'training-courses.course-batches.success.deleted': 'training-courses.course-batches.success.deleted',
  'training-courses.person-course-batches.errors.already_enrolled': 'training-courses.person-course-batches.errors.already_enrolled',
  'training-courses.person-course-batches.errors.drop_out_date_before_join_date': 'training-courses.person-course-batches.errors.drop_out_date_before_join_date',
  'training-courses.person-course-batches.errors.not_found': 'training-courses.person-course-batches.errors.not_found',
  'training-courses.person-course-batches.success.deleted': 'training-courses.person-course-batches.success.deleted',
  'training-courses.training-courses.errors.name_exists': 'training-courses.training-courses.errors.name_exists',
  'training-courses.training-courses.errors.not_found': 'training-courses.training-courses.errors.not_found',
  'training-courses.training-courses.success.deleted': 'training-courses.training-courses.success.deleted',
  'uploads.errors.delete_failed': 'uploads.errors.delete_failed',
  'uploads.errors.not_found': 'uploads.errors.not_found',
  'uploads.errors.upload_failed': 'uploads.errors.upload_failed'
} as const;

export type TranslationKey = keyof typeof TranslationKeys;

// Type definitions for interpolation parameters
type NoParams = undefined;

// Placeholder type for type-safe interpolation
export interface TranslationInterpolations {
  'app.hello_world': NoParams;
  'auth.errors.invalid_credentials': NoParams;
  'auth.errors.invalid_or_expired_access_token': NoParams;
  'dropdowns.errors.cannot_create_subcategory': NoParams;
  'dropdowns.errors.cannot_delete_core_category': NoParams;
  'dropdowns.errors.cannot_delete_dropdown_referenced': DropdownsErrorsCannotdeletedropdownreferencedParams;
  'dropdowns.errors.cannot_delete_option_referenced': DropdownsErrorsCannotdeleteoptionreferencedParams;
  'dropdowns.errors.cannot_update_options_not_found': DropdownsErrorsCannotupdateoptionsnotfoundParams;
  'dropdowns.errors.category_has_children': NoParams;
  'dropdowns.errors.category_has_dropdowns': NoParams;
  'dropdowns.errors.category_mismatch': DropdownsErrorsCategorymismatchParams;
  'dropdowns.errors.category_name_exists': DropdownsErrorsCategorynameexistsParams;
  'dropdowns.errors.category_not_found': DropdownsErrorsCategorynotfoundParams;
  'dropdowns.errors.dropdown_has_options': NoParams;
  'dropdowns.errors.dropdown_name_exists': DropdownsErrorsDropdownnameexistsParams;
  'dropdowns.errors.dropdown_not_found': DropdownsErrorsDropdownnotfoundParams;
  'dropdowns.errors.dropdown_not_found_in_category': DropdownsErrorsDropdownnotfoundincategoryParams;
  'dropdowns.errors.duplicate_option_names_in_request': DropdownsErrorsDuplicateoptionnamesinrequestParams;
  'dropdowns.errors.duplicate_options_not_allowed': NoParams;
  'dropdowns.errors.invalid_selection_type': NoParams;
  'dropdowns.errors.max_depth_exceeded': DropdownsErrorsMaxdepthexceededParams;
  'dropdowns.errors.multiple_selection_requires_at_least_one_option': NoParams;
  'dropdowns.errors.option_has_selections': NoParams;
  'dropdowns.errors.option_name_already_exists': DropdownsErrorsOptionnamealreadyexistsParams;
  'dropdowns.errors.option_name_exists': DropdownsErrorsOptionnameexistsParams;
  'dropdowns.errors.option_not_found': DropdownsErrorsOptionnotfoundParams;
  'dropdowns.errors.option_not_found_in_dropdown': DropdownsErrorsOptionnotfoundindropdownParams;
  'dropdowns.errors.option_not_in_dropdown': DropdownsErrorsOptionnotindropdownParams;
  'dropdowns.errors.selection_not_found': DropdownsErrorsSelectionnotfoundParams;
  'dropdowns.errors.single_selection_exists': NoParams;
  'dropdowns.errors.single_selection_requires_one_option': NoParams;
  'emergency-aid-request.errors.cannot_approve_non_pending': NoParams;
  'emergency-aid-request.errors.cannot_cancel_unmodifiable': NoParams;
  'emergency-aid-request.errors.cannot_disburse_non_approved': NoParams;
  'emergency-aid-request.errors.cannot_reject_non_pending': NoParams;
  'emergency-aid-request.errors.not_found': EmergencyaidrequestErrorsNotfoundParams;
  'employees.errors.already_employee': NoParams;
  'employees.errors.cannot_delete_with_system_account': NoParams;
  'employees.errors.not_found': EmployeesErrorsNotfoundParams;
  'families.family_book_number_exists': NoParams;
  'families.family_book_number_exists_another': NoParams;
  'families.form_number_exists': NoParams;
  'families.form_number_exists_another': NoParams;
  'families.not_found': NoParams;
  'families.request_number_exists': NoParams;
  'families.request_number_exists_another': NoParams;
  'family-members.errors.cannot_change_relation_with_sponsorships': NoParams;
  'family-members.errors.family_already_has_father': NoParams;
  'family-members.errors.family_already_has_guardian': NoParams;
  'family-members.errors.gender_relation_mismatch': NoParams;
  'family-members.errors.not_found': NoParams;
  'family-members.errors.not_found_with_id': FamilymembersErrorsNotfoundwithidParams;
  'family-members.errors.only_children_can_be_sponsored': NoParams;
  'family-members.errors.person_already_family_member': NoParams;
  'family-needs.errors.not_found': NoParams;
  'guards.errors.access_denied': GuardsErrorsAccessdeniedParams;
  'guards.errors.access_token_required': NoParams;
  'guards.errors.token_issued_before_login': NoParams;
  'guards.errors.token_issued_before_password_change': NoParams;
  'guards.errors.user_not_authenticated': NoParams;
  'interviews.errors.not_found': NoParams;
  'persons.errors.email_exists': NoParams;
  'persons.errors.father_name_exists': NoParams;
  'persons.errors.full_name_exists': NoParams;
  'persons.errors.name_no_parent_exists': NoParams;
  'persons.errors.national_id_exists': NoParams;
  'persons.errors.not_found': PersonsErrorsNotfoundParams;
  'persons.errors.not_found_by_name': PersonsErrorsNotfoundbynameParams;
  'persons.errors.person_details_exists': NoParams;
  'pipes.validation.array_required': NoParams;
  'pipes.validation.exactly_one_of_fields': PipesValidationExactlyoneoffieldsParams;
  'pipes.validation.id_integer': NoParams;
  'pipes.validation.id_not_empty': NoParams;
  'pipes.validation.id_positive': NoParams;
  'pipes.validation.invalid_boolean_value': PipesValidationInvalidbooleanvalueParams;
  'pipes.validation.invalid_syria_phone': PipesValidationInvalidsyriaphoneParams;
  'pipes.validation.is_less_than_or_equal': PipesValidationIslessthanorequalParams;
  'pipes.validation.max_greater_than_or_equal_min': PipesValidationMaxgreaterthanorequalminParams;
  'pipes.validation.min_max_validation_failed': NoParams;
  'pipes.validation.multiple_validation_errors': PipesValidationMultiplevalidationerrorsParams;
  'pipes.validation.must_not_equal': PipesValidationMustnotequalParams;
  'pipes.validation.only_one_of_fields': PipesValidationOnlyoneoffieldsParams;
  'pipes.validation.positive_integer_required': NoParams;
  'received-assistance.errors.family_member_mismatch': NoParams;
  'received-assistance.errors.not_found': ReceivedassistanceErrorsNotfoundParams;
  'roles.errors.cannot_change_superadmin_permissions': NoParams;
  'roles.errors.cannot_modify_protected_users': NoParams;
  'roles.errors.duplicate_permission_ids': RolesErrorsDuplicatepermissionidsParams;
  'roles.errors.permission_ids_not_exist': NoParams;
  'roles.errors.permission_not_assigned': RolesErrorsPermissionnotassignedParams;
  'roles.errors.permission_not_found': RolesErrorsPermissionnotfoundParams;
  'roles.errors.permissions_not_found': RolesErrorsPermissionsnotfoundParams;
  'roles.errors.role_has_users': NoParams;
  'roles.errors.role_name_exists': RolesErrorsRolenameexistsParams;
  'roles.errors.role_name_in_use': RolesErrorsRolenameinuseParams;
  'roles.errors.role_not_found': RolesErrorsRolenotfoundParams;
  'roles.errors.role_protected': NoParams;
  'roles.errors.superadmin_role_protected': NoParams;
  'roles.errors.system_user_not_found': RolesErrorsSystemusernotfoundParams;
  'roles.errors.user_not_found': RolesErrorsUsernotfoundParams;
  'supporters.errors.already_supporter': NoParams;
  'supporters.errors.child_sponsorship.child_already_has_active_sponsorship': NoParams;
  'supporters.errors.child_sponsorship.child_already_sponsored': NoParams;
  'supporters.errors.child_sponsorship.not_found': SupportersErrorsChildsponsorshipNotfoundParams;
  'supporters.errors.child_sponsorship.only_children_can_be_sponsored': NoParams;
  'supporters.errors.not_found': SupportersErrorsNotfoundParams;
  'system-users.errors.employee_has_system_account': NoParams;
  'system-users.errors.not_found': SystemusersErrorsNotfoundParams;
  'system-users.errors.username_taken': NoParams;
  'system-users.success.deleted': SystemusersSuccessDeletedParams;
  'training-courses.course-batches.errors.batch_number_exists': TrainingcoursesCoursebatchesErrorsBatchnumberexistsParams;
  'training-courses.course-batches.errors.end_date_before_start_date': NoParams;
  'training-courses.course-batches.errors.not_found': TrainingcoursesCoursebatchesErrorsNotfoundParams;
  'training-courses.course-batches.success.deleted': TrainingcoursesCoursebatchesSuccessDeletedParams;
  'training-courses.person-course-batches.errors.already_enrolled': TrainingcoursesPersoncoursebatchesErrorsAlreadyenrolledParams;
  'training-courses.person-course-batches.errors.drop_out_date_before_join_date': NoParams;
  'training-courses.person-course-batches.errors.not_found': TrainingcoursesPersoncoursebatchesErrorsNotfoundParams;
  'training-courses.person-course-batches.success.deleted': NoParams;
  'training-courses.training-courses.errors.name_exists': NoParams;
  'training-courses.training-courses.errors.not_found': TrainingcoursesTrainingcoursesErrorsNotfoundParams;
  'training-courses.training-courses.success.deleted': TrainingcoursesTrainingcoursesSuccessDeletedParams;
  'uploads.errors.delete_failed': NoParams;
  'uploads.errors.not_found': UploadsErrorsNotfoundParams;
  'uploads.errors.upload_failed': NoParams;
}
