// Generated by i18n-validator

interface GuardsErrorsAccessdeniedParams {
  permissions: string | number
}

interface PipesValidationIslessthanorequalParams {
  property: string | number; relatedProperty: string | number
}

interface PipesValidationOnlyoneoffieldsParams {
  fields: string | number
}

interface PipesValidationExactlyoneoffieldsParams {
  fields: string | number
}

interface PipesValidationMultiplevalidationerrorsParams {
  errors: string | number
}

interface PipesValidationMaxgreaterthanorequalminParams {
  maxField: string | number; maxValue: string | number; minField: string | number; minValue: string | number
}

interface PipesValidationInvalidsyriaphoneParams {
  property: string | number
}

interface PipesValidationInvalidbooleanvalueParams {
  key: string | number
}

interface PipesValidationMustnotequalParams {
  property: string | number; relatedProperty: string | number
}

const TranslationKeys = {
  'app.hello_world': 'app.hello_world',
  'auth.errors.invalid_credentials': 'auth.errors.invalid_credentials',
  'auth.errors.invalid_or_expired_access_token': 'auth.errors.invalid_or_expired_access_token',
  'guards.errors.access_denied': 'guards.errors.access_denied',
  'guards.errors.access_token_required': 'guards.errors.access_token_required',
  'guards.errors.token_issued_before_login': 'guards.errors.token_issued_before_login',
  'guards.errors.token_issued_before_password_change': 'guards.errors.token_issued_before_password_change',
  'guards.errors.user_not_authenticated': 'guards.errors.user_not_authenticated',
  'pipes.validation.array_required': 'pipes.validation.array_required',
  'pipes.validation.exactly_one_of_fields': 'pipes.validation.exactly_one_of_fields',
  'pipes.validation.id_integer': 'pipes.validation.id_integer',
  'pipes.validation.id_not_empty': 'pipes.validation.id_not_empty',
  'pipes.validation.id_positive': 'pipes.validation.id_positive',
  'pipes.validation.invalid_boolean_value': 'pipes.validation.invalid_boolean_value',
  'pipes.validation.invalid_syria_phone': 'pipes.validation.invalid_syria_phone',
  'pipes.validation.is_less_than_or_equal': 'pipes.validation.is_less_than_or_equal',
  'pipes.validation.max_greater_than_or_equal_min': 'pipes.validation.max_greater_than_or_equal_min',
  'pipes.validation.min_max_validation_failed': 'pipes.validation.min_max_validation_failed',
  'pipes.validation.multiple_validation_errors': 'pipes.validation.multiple_validation_errors',
  'pipes.validation.must_not_equal': 'pipes.validation.must_not_equal',
  'pipes.validation.only_one_of_fields': 'pipes.validation.only_one_of_fields',
  'pipes.validation.positive_integer_required': 'pipes.validation.positive_integer_required'
} as const;

export type TranslationKey = keyof typeof TranslationKeys;

// Type definitions for interpolation parameters
type NoParams = undefined;

// Placeholder type for type-safe interpolation
export interface TranslationInterpolations {
  'app.hello_world': NoParams;
  'auth.errors.invalid_credentials': NoParams;
  'auth.errors.invalid_or_expired_access_token': NoParams;
  'guards.errors.access_denied': GuardsErrorsAccessdeniedParams;
  'guards.errors.access_token_required': NoParams;
  'guards.errors.token_issued_before_login': NoParams;
  'guards.errors.token_issued_before_password_change': NoParams;
  'guards.errors.user_not_authenticated': NoParams;
  'pipes.validation.array_required': NoParams;
  'pipes.validation.exactly_one_of_fields': PipesValidationExactlyoneoffieldsParams;
  'pipes.validation.id_integer': NoParams;
  'pipes.validation.id_not_empty': NoParams;
  'pipes.validation.id_positive': NoParams;
  'pipes.validation.invalid_boolean_value': PipesValidationInvalidbooleanvalueParams;
  'pipes.validation.invalid_syria_phone': PipesValidationInvalidsyriaphoneParams;
  'pipes.validation.is_less_than_or_equal': PipesValidationIslessthanorequalParams;
  'pipes.validation.max_greater_than_or_equal_min': PipesValidationMaxgreaterthanorequalminParams;
  'pipes.validation.min_max_validation_failed': NoParams;
  'pipes.validation.multiple_validation_errors': PipesValidationMultiplevalidationerrorsParams;
  'pipes.validation.must_not_equal': PipesValidationMustnotequalParams;
  'pipes.validation.only_one_of_fields': PipesValidationOnlyoneoffieldsParams;
  'pipes.validation.positive_integer_required': NoParams;
}
