// Generated by i18n-validator

interface TestValidationLENGTHParams {
  constraints_0: string;
  constraints_1: string;
}

interface TestValidationMINLENGTHParams {
  min: string;
}

interface TestValidationMAXLENGTHParams {
  max: string;
}

interface TestValidationMINParams {
  min: string;
}

interface TestValidationMAXParams {
  max: string;
}

const TranslationKeys = {
  'test.errors.network': 'test.errors.network',
  'test.errors.not_found': 'test.errors.not_found',
  'test.errors.unauthorized': 'test.errors.unauthorized',
  'test.success.data_saved': 'test.success.data_saved',
  'test.success.operation_completed': 'test.success.operation_completed',
  'test.validation.EMAIL': 'test.validation.EMAIL',
  'test.validation.IS_BOOLEAN': 'test.validation.IS_BOOLEAN',
  'test.validation.IS_DATE': 'test.validation.IS_DATE',
  'test.validation.IS_NUMBER': 'test.validation.IS_NUMBER',
  'test.validation.IS_REQUIRED': 'test.validation.IS_REQUIRED',
  'test.validation.LENGTH': 'test.validation.LENGTH',
  'test.validation.MATCH': 'test.validation.MATCH',
  'test.validation.MAX': 'test.validation.MAX',
  'test.validation.MAX_LENGTH': 'test.validation.MAX_LENGTH',
  'test.validation.MIN': 'test.validation.MIN',
  'test.validation.MIN_LENGTH': 'test.validation.MIN_LENGTH',
  'test.validation.MUST_BE_STRING': 'test.validation.MUST_BE_STRING',
} as const;

export type TranslationKey = keyof typeof TranslationKeys;

// Type definitions for interpolation parameters
type NoParams = undefined;

// Placeholder type for type-safe interpolation
export interface TranslationInterpolations {
  'test.errors.network': NoParams;
  'test.errors.not_found': NoParams;
  'test.errors.unauthorized': NoParams;
  'test.success.data_saved': NoParams;
  'test.success.operation_completed': NoParams;
  'test.validation.EMAIL': NoParams;
  'test.validation.IS_BOOLEAN': NoParams;
  'test.validation.IS_DATE': NoParams;
  'test.validation.IS_NUMBER': NoParams;
  'test.validation.IS_REQUIRED': NoParams;
  'test.validation.LENGTH': TestValidationLENGTHParams;
  'test.validation.MATCH': NoParams;
  'test.validation.MAX': TestValidationMAXParams;
  'test.validation.MAX_LENGTH': TestValidationMAXLENGTHParams;
  'test.validation.MIN': TestValidationMINParams;
  'test.validation.MIN_LENGTH': TestValidationMINLENGTHParams;
  'test.validation.MUST_BE_STRING': NoParams;
}
